[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click==8.2.1",
    "mkdocs-material>=9.7.1",
    "mkdocs-video>=1.5.0",
    "zensical>=0.0.18",
]
